## 读写分离配置
spring:
  shardingsphere:
    datasource:
      names: master
      ## 主库
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/plus_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    props:
      sql:
        show: true

## 逻辑删除配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jwt:
  header: Authorization
  claim: username
  expiration: 60000
  issuer: JWT
  secret: 432d2eb**************20dba3633

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-group